### ISSUE TITLE
Camera params

### ISSUE THREAD

**Issue by RuslanOm** [TJ-IPLab/DNet#6]
Hi, thanks for a great model!
Can you please explain how you got a Intrinsic parameters and how I can get this params for random image from different camera?

Thanks!

**Comment by josephxue** [comment]
Hi 

Intrinsic parameter can be downloaded freely on KITTI dataset website, an example link may be https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_calib.zip. But in this repository, we calculate the average intrinsic parameter following our baseline model Monodepth2.

Because this model does not estimate intrinsic parameters, so these parameters can only be prepared in advance. So you may calibrate your own camera first.

**Comment by RuslanOm** [comment]
Ok, thanks!
